name: ci

on:
  push:
    branches:
      - main
      - poetry
  pull_request:
    branches:
      - main
      - poetry

defaults:
  run:
    working-directory: main

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - run: poetry run mypy --namespace-packages -p ampel
